### ISSUE TITLE
Consider switching to a more friendly license

### ISSUE THREAD

**Issue by TimTheTinker** [mperdeck/LINQtoCSV#37]
Hello,

May I suggest switching this project to the BSD or Apache 2.0 license. The Code Project Open License (CPOL) has some legal weirdnesses (see http://stackoverflow.com/questions/698610/is-the-code-project-open-license-a-gpl-compatible-license) that people might find uncomfortable.

Thanks!
-Roy

**Comment by TimTheTinker** [comment]
Or the BSD license would be just as good.

**Comment by TimTheTinker** [comment]
Also, the FSF says the CPOL is "not a free software license": https://www.gnu.org/licenses/license-list.html#cpol

**Comment by mperdeck** [comment]
Hi Roy,

Thanks for the heads up about CPOL. When I wrote the articles on the Code Project, I didn't consider the license, which gave me the default, which is CPOL.

For the record - the license that applies to the JSNLog package is the one shown in the footer of the jsnlog.com web site. Any other licenses, such as those attached to articles about JSNLog, are not relevant.

If you have a look at the footer of jsnlog.com, you'll find that currently it says Apache 2.0. I've used that from the beginning.

Please let me know if this resolves your concerns.

Matt

**Comment by mperdeck** [comment]
Hi Roy,

My apologies, I thought your post was about my latest project JSNLog rather than LINQtoCSV.

I've changed the license on the CodeProject article to Apache.

Matt

**Comment by TimTheTinker** [comment]
Matt, thanks so much!
