### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by DigitalFlow** [mperdeck/LINQtoCSV#58]
Hey there,

thanks for this project.

Would it be possible to add a license, such as the MIT license, for making this project usable in company solutions?

Kind Regards,
Florian

**Comment by cezarypiatek** [comment]
In accompanying article there is a licence information but I'm not sure if this is only an article or also source code licence: https://www.codeproject.com/Articles/25133/LINQ-to-CSV-library
This could be very helpful if github project and nuget package have licence information.

**Comment by mperdeck** [comment]
I've added the license to the Github project:
https://github.com/mperdeck/LINQtoCSV

**Comment by cezarypiatek** [comment]
@mperdeck  thanks for your help. 
Could you also add  link to licence file inside the nuget packages? 
Licence file could be created as follows https://help.github.com/articles/adding-a-license-to-a-repository/
